// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");

var linen = /* String */Block.__(0, ["#EAE2D6"]);

var oyster = /* String */Block.__(0, ["#D5C3AA"]);

var pewter = /* String */Block.__(0, ["#86766"]);

var lemonTea = /* String */Block.__(0, ["#E1B80D"]);

exports.linen = linen;
exports.oyster = oyster;
exports.pewter = pewter;
exports.lemonTea = lemonTea;
/* No side effect */
