// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var Text$BsReactNative = require("bs-react-native/lib/js/src/components/text.js");
var View$BsReactNative = require("bs-react-native/lib/js/src/components/view.js");
var Style$BsReactNative = require("bs-react-native/lib/js/src/style.js");
var Animated$BsReactNative = require("bs-react-native/lib/js/src/animated.js");
var Dimensions$BsReactNative = require("bs-react-native/lib/js/src/dimensions.js");
var AnimatedComponents$BsReactNative = require("bs-react-native/lib/js/src/components/animatedComponents.js");

var screenWidth = Dimensions$BsReactNative.get(/* window */-762539024).width;

function renderHorizontalStepMarker(step) {
  return ReasonReact.element(undefined, undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(Style$BsReactNative.style(/* :: */[
                            Style$BsReactNative.position(/* Absolute */0),
                            /* :: */[
                              Style$BsReactNative.borderRadius(15),
                              /* :: */[
                                Style$BsReactNative.left(/* Pt */Block.__(0, [step * 100 + 2.5])),
                                /* :: */[
                                  Style$BsReactNative.top(/* Pt */Block.__(0, [24.5])),
                                  /* :: */[
                                    Style$BsReactNative.width(/* Pt */Block.__(0, [15])),
                                    /* :: */[
                                      Style$BsReactNative.height(/* Pt */Block.__(0, [15])),
                                      /* :: */[
                                        Style$BsReactNative.backgroundColor(/* String */Block.__(0, ["white"])),
                                        /* [] */0
                                      ]
                                    ]
                                  ]
                                ]
                              ]
                            ]
                          ])), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[]));
}

var component = ReasonReact.reducerComponentWithRetainedProps("DropDownBar");

function make(shouldTriggerAnim, step, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */(function (param) {
              var newSelf = param[/* newSelf */1];
              if (param[/* oldSelf */0][/* retainedProps */2][/* shouldTriggerAnim */0] !== newSelf[/* retainedProps */2][/* shouldTriggerAnim */0]) {
                Curry._1(newSelf[/* send */3], /* ResetValue */0);
                return Curry._1(newSelf[/* send */3], /* TriggerAnim */[newSelf[/* retainedProps */2][/* shouldTriggerAnim */0]]);
              } else {
                return 0;
              }
            }),
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              var match = step === 1;
              var tmp;
              if (match) {
                tmp = renderHorizontalStepMarker(step);
              } else {
                var match$1 = step === 2;
                tmp = match$1 ? renderHorizontalStepMarker(step) : ReasonReact.element(undefined, undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[]));
              }
              return ReasonReact.element(undefined, undefined, Curry.app(AnimatedComponents$BsReactNative.View[/* make */0], [
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              Js_primitive.some(Style$BsReactNative.style(/* :: */[
                                        Style$BsReactNative.flex(1),
                                        /* :: */[
                                          Style$BsReactNative.position(/* Absolute */0),
                                          /* :: */[
                                            Style$BsReactNative.width(/* Pt */Block.__(0, [screenWidth])),
                                            /* :: */[
                                              Style$BsReactNative.paddingHorizontal(/* Pt */Block.__(0, [10])),
                                              /* :: */[
                                                Style$BsReactNative.flexDirection(/* Column */2),
                                                /* :: */[
                                                  Style$BsReactNative.alignItems(/* Center */2),
                                                  /* :: */[
                                                    Style$BsReactNative.height(/* Pt */Block.__(0, [70])),
                                                    /* :: */[
                                                      Style$BsReactNative.backgroundColor(/* String */Block.__(0, ["#867666C9"])),
                                                      /* :: */[
                                                        Style$BsReactNative.Transform[/* makeInterpolated */2](undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(Curry._8(Animated$BsReactNative.Value[/* interpolate */10], self[/* state */1][/* translateX */2], /* :: */[
                                                                      0,
                                                                      /* :: */[
                                                                        1,
                                                                        /* [] */0
                                                                      ]
                                                                    ], /* `float */[
                                                                      43435420,
                                                                      shouldTriggerAnim ? /* :: */[
                                                                          -150,
                                                                          /* :: */[
                                                                            0,
                                                                            /* [] */0
                                                                          ]
                                                                        ] : /* :: */[
                                                                          0,
                                                                          /* :: */[
                                                                            -150,
                                                                            /* [] */0
                                                                          ]
                                                                        ]
                                                                    ], undefined, undefined, undefined, undefined, /* () */0)), undefined, undefined, /* () */0),
                                                        /* [] */0
                                                      ]
                                                    ]
                                                  ]
                                                ]
                                              ]
                                            ]
                                          ]
                                        ]
                                      ])),
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              /* array */[
                                ReasonReact.element(undefined, undefined, Text$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(Style$BsReactNative.style(/* :: */[
                                                  Style$BsReactNative.color(/* String */Block.__(0, ["white"])),
                                                  /* :: */[
                                                    Style$BsReactNative.fontSize(/* Float */Block.__(0, [14])),
                                                    /* :: */[
                                                      Style$BsReactNative.paddingRight(/* Pt */Block.__(0, [5])),
                                                      /* [] */0
                                                    ]
                                                  ]
                                                ])), undefined, undefined, undefined, undefined, undefined, undefined, "Add just bit more: ", /* array */[])),
                                ReasonReact.element(undefined, undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(Style$BsReactNative.style(/* :: */[
                                                    Style$BsReactNative.flex(1),
                                                    /* :: */[
                                                      Style$BsReactNative.alignItems(/* Center */2),
                                                      /* :: */[
                                                        Style$BsReactNative.marginTop(/* Pt */Block.__(0, [-15])),
                                                        /* :: */[
                                                          Style$BsReactNative.flexDirection(/* Row */0),
                                                          /* :: */[
                                                            Style$BsReactNative.height(/* Pt */Block.__(0, [20.0])),
                                                            /* :: */[
                                                              Style$BsReactNative.justifyContent(/* Center */2),
                                                              /* [] */0
                                                            ]
                                                          ]
                                                        ]
                                                      ]
                                                    ]
                                                  ])), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[
                                          ReasonReact.element(undefined, undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(Style$BsReactNative.style(/* :: */[
                                                              Style$BsReactNative.flex(1),
                                                              /* :: */[
                                                                Style$BsReactNative.borderRadius(5),
                                                                /* :: */[
                                                                  Style$BsReactNative.height(/* Pt */Block.__(0, [5.0])),
                                                                  /* :: */[
                                                                    Style$BsReactNative.backgroundColor(/* String */Block.__(0, ["#E1B80D"])),
                                                                    /* [] */0
                                                                  ]
                                                                ]
                                                              ]
                                                            ])), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[])),
                                          ReasonReact.element(undefined, undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(Style$BsReactNative.style(/* :: */[
                                                              Style$BsReactNative.position(/* Absolute */0),
                                                              /* :: */[
                                                                Style$BsReactNative.borderRadius(10),
                                                                /* :: */[
                                                                  Style$BsReactNative.left(/* Pt */Block.__(0, [100])),
                                                                  /* :: */[
                                                                    Style$BsReactNative.top(/* Pt */Block.__(0, [22])),
                                                                    /* :: */[
                                                                      Style$BsReactNative.width(/* Pt */Block.__(0, [20])),
                                                                      /* :: */[
                                                                        Style$BsReactNative.height(/* Pt */Block.__(0, [20])),
                                                                        /* :: */[
                                                                          Style$BsReactNative.backgroundColor(/* String */Block.__(0, ["#E1B80D"])),
                                                                          /* [] */0
                                                                        ]
                                                                      ]
                                                                    ]
                                                                  ]
                                                                ]
                                                              ]
                                                            ])), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[])),
                                          ReasonReact.element(undefined, undefined, Text$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(Style$BsReactNative.style(/* :: */[
                                                            Style$BsReactNative.color(/* String */Block.__(0, ["white"])),
                                                            /* :: */[
                                                              Style$BsReactNative.fontSize(/* Float */Block.__(0, [15])),
                                                              /* :: */[
                                                                Style$BsReactNative.position(/* Absolute */0),
                                                                /* :: */[
                                                                  Style$BsReactNative.left(/* Pt */Block.__(0, [100])),
                                                                  /* :: */[
                                                                    Style$BsReactNative.top(/* Pt */Block.__(0, [40])),
                                                                    /* [] */0
                                                                  ]
                                                                ]
                                                              ]
                                                            ]
                                                          ])), undefined, undefined, undefined, undefined, undefined, undefined, "1/3 ", /* array */[])),
                                          ReasonReact.element(undefined, undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(Style$BsReactNative.style(/* :: */[
                                                              Style$BsReactNative.position(/* Absolute */0),
                                                              /* :: */[
                                                                Style$BsReactNative.borderRadius(10),
                                                                /* :: */[
                                                                  Style$BsReactNative.left(/* Pt */Block.__(0, [200])),
                                                                  /* :: */[
                                                                    Style$BsReactNative.top(/* Pt */Block.__(0, [22])),
                                                                    /* :: */[
                                                                      Style$BsReactNative.width(/* Pt */Block.__(0, [20])),
                                                                      /* :: */[
                                                                        Style$BsReactNative.height(/* Pt */Block.__(0, [20])),
                                                                        /* :: */[
                                                                          Style$BsReactNative.backgroundColor(/* String */Block.__(0, ["#E1B80D"])),
                                                                          /* [] */0
                                                                        ]
                                                                      ]
                                                                    ]
                                                                  ]
                                                                ]
                                                              ]
                                                            ])), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[])),
                                          ReasonReact.element(undefined, undefined, Text$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(Style$BsReactNative.style(/* :: */[
                                                            Style$BsReactNative.color(/* String */Block.__(0, ["white"])),
                                                            /* :: */[
                                                              Style$BsReactNative.fontSize(/* Float */Block.__(0, [15])),
                                                              /* :: */[
                                                                Style$BsReactNative.position(/* Absolute */0),
                                                                /* :: */[
                                                                  Style$BsReactNative.left(/* Pt */Block.__(0, [200])),
                                                                  /* :: */[
                                                                    Style$BsReactNative.top(/* Pt */Block.__(0, [40])),
                                                                    /* [] */0
                                                                  ]
                                                                ]
                                                              ]
                                                            ]
                                                          ])), undefined, undefined, undefined, undefined, undefined, undefined, "1/4 ", /* array */[])),
                                          tmp
                                        ]))
                              ]
                            ]));
            }),
          /* initialState */(function () {
              return /* record */[
                      /* shouldAnim */false,
                      /* triggerAnim */false,
                      /* translateX */Curry._1(Animated$BsReactNative.Value[/* create */0], -150)
                    ];
            }),
          /* retainedProps : record */[/* shouldTriggerAnim */shouldTriggerAnim],
          /* reducer */(function (action, state) {
              if (action) {
                var animation = Animated$BsReactNative.timing(state[/* translateX */2], /* `raw */[
                      5690856,
                      1.0
                    ], undefined, 500.0, undefined, undefined, undefined, undefined, undefined, /* () */0);
                Animated$BsReactNative.start(animation, undefined, (console.log("Complete"), /* () */0));
                return /* Update */Block.__(0, [/* record */[
                            /* shouldAnim */state[/* shouldAnim */0],
                            /* triggerAnim */action[0],
                            /* translateX */state[/* translateX */2]
                          ]]);
              } else {
                return /* Update */Block.__(0, [/* record */[
                            /* shouldAnim */state[/* shouldAnim */0],
                            /* triggerAnim */state[/* triggerAnim */1],
                            /* translateX */Curry._1(Animated$BsReactNative.Value[/* create */0], 0)
                          ]]);
              }
            }),
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

var reverser = /* record */[
  /* forward : :: */[
    -150,
    /* :: */[
      0,
      /* [] */0
    ]
  ],
  /* backwards : :: */[
    0,
    /* :: */[
      -150,
      /* [] */0
    ]
  ]
];

exports.screenWidth = screenWidth;
exports.reverser = reverser;
exports.renderHorizontalStepMarker = renderHorizontalStepMarker;
exports.component = component;
exports.make = make;
/* screenWidth Not a pure module */
