// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var Text$BsReactNative = require("bs-react-native/lib/js/src/components/text.js");
var View$BsReactNative = require("bs-react-native/lib/js/src/components/view.js");
var Style$BsReactNative = require("bs-react-native/lib/js/src/style.js");
var Animated$BsReactNative = require("bs-react-native/lib/js/src/animated.js");
var AnimatedComponents$BsReactNative = require("bs-react-native/lib/js/src/components/animatedComponents.js");
var TouchableWithoutFeedback$BsReactNative = require("bs-react-native/lib/js/src/components/touchableWithoutFeedback.js");

var component = ReasonReact.reducerComponent("FractionBubble");

function make(style, text, onPress, diameter, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              Curry._1(Animated$BsReactNative.Value[/* create */0], 0);
              var newStyle = Style$BsReactNative.combine(style, Style$BsReactNative.style(/* :: */[
                        Style$BsReactNative.justifyContent(/* Center */2),
                        /* :: */[
                          Style$BsReactNative.alignItems(/* Center */2),
                          /* :: */[
                            Style$BsReactNative.borderRadius(diameter),
                            /* :: */[
                              Style$BsReactNative.width(/* Pt */Block.__(0, [diameter])),
                              /* :: */[
                                Style$BsReactNative.height(/* Pt */Block.__(0, [diameter])),
                                /* :: */[
                                  Style$BsReactNative.Transform[/* makeInterpolated */2](undefined, undefined, undefined, undefined, undefined, Js_primitive.some(Curry._8(Animated$BsReactNative.Value[/* interpolate */10], self[/* state */1][/* animation */0], /* :: */[
                                                0,
                                                /* :: */[
                                                  1,
                                                  /* [] */0
                                                ]
                                              ], /* `float */[
                                                43435420,
                                                /* :: */[
                                                  1,
                                                  /* :: */[
                                                    1.25,
                                                    /* [] */0
                                                  ]
                                                ]
                                              ], undefined, undefined, undefined, undefined, /* () */0)), Js_primitive.some(Curry._8(Animated$BsReactNative.Value[/* interpolate */10], self[/* state */1][/* animation */0], /* :: */[
                                                0,
                                                /* :: */[
                                                  1,
                                                  /* [] */0
                                                ]
                                              ], /* `float */[
                                                43435420,
                                                /* :: */[
                                                  1,
                                                  /* :: */[
                                                    1.25,
                                                    /* [] */0
                                                  ]
                                                ]
                                              ], undefined, undefined, undefined, undefined, /* () */0)), undefined, undefined, undefined, undefined, /* () */0),
                                  /* [] */0
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]));
              return ReasonReact.element(undefined, undefined, Curry.app(AnimatedComponents$BsReactNative.View[/* make */0], [
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              Js_primitive.some(newStyle),
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              /* array */[ReasonReact.element(undefined, undefined, TouchableWithoutFeedback$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, (function () {
                                              console.log("pressed");
                                              Curry._1(self[/* send */3], /* Spring */0);
                                              return Curry._1(onPress, /* () */0);
                                            }), (function () {
                                              console.log("innnn");
                                              return Curry._1(self[/* send */3], /* StartAnim */[true]);
                                            }), (function () {
                                              console.log("out");
                                              return Curry._1(self[/* send */3], /* StartAnim */[false]);
                                            }), undefined, Js_primitive.some(newStyle))(/* array */[ReasonReact.element(undefined, undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(Style$BsReactNative.style(/* :: */[
                                                              Style$BsReactNative.width(/* Pt */Block.__(0, [diameter])),
                                                              /* :: */[
                                                                Style$BsReactNative.height(/* Pt */Block.__(0, [diameter])),
                                                                /* :: */[
                                                                  Style$BsReactNative.borderRadius(diameter),
                                                                  /* :: */[
                                                                    Style$BsReactNative.justifyContent(/* Center */2),
                                                                    /* :: */[
                                                                      Style$BsReactNative.alignItems(/* Center */2),
                                                                      /* [] */0
                                                                    ]
                                                                  ]
                                                                ]
                                                              ]
                                                            ])), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[ReasonReact.element(undefined, undefined, Text$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(Style$BsReactNative.style(/* :: */[
                                                                      Style$BsReactNative.color(/* String */Block.__(0, ["white"])),
                                                                      /* :: */[
                                                                        Style$BsReactNative.fontSize(/* Float */Block.__(0, [14])),
                                                                        /* [] */0
                                                                      ]
                                                                    ])), undefined, undefined, undefined, undefined, undefined, undefined, text, /* array */[]))]))]))]
                            ]));
            }),
          /* initialState */(function () {
              return /* record */[
                      /* animation */Curry._1(Animated$BsReactNative.Value[/* create */0], 0),
                      /* played */false
                    ];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              if (action) {
                var animation = Animated$BsReactNative.timing(state[/* animation */0], /* `raw */[
                      5690856,
                      action[0] ? 1.0 : 0
                    ], undefined, 100.0, undefined, undefined, undefined, undefined, undefined, /* () */0);
                Animated$BsReactNative.start(animation, undefined, /* () */0);
                return /* Update */Block.__(0, [/* record */[
                            /* animation */state[/* animation */0],
                            /* played */!state[/* played */1]
                          ]]);
              } else {
                var animation$1 = Animated$BsReactNative.spring(state[/* animation */0], /* `raw */[
                      5690856,
                      0.0
                    ], undefined, undefined, undefined, undefined, undefined, undefined, 35, 3.5, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* () */0);
                Animated$BsReactNative.start(animation$1, undefined, /* () */0);
                return /* Update */Block.__(0, [/* record */[
                            /* animation */state[/* animation */0],
                            /* played */!state[/* played */1]
                          ]]);
              }
            }),
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
