// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Colors = require("./Colors.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var Text$BsReactNative = require("bs-react-native/lib/js/src/components/text.js");
var Style$BsReactNative = require("bs-react-native/lib/js/src/style.js");
var Animated$BsReactNative = require("bs-react-native/lib/js/src/animated.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");
var AnimatedComponents$BsReactNative = require("bs-react-native/lib/js/src/components/animatedComponents.js");

var component = ReasonReact.reducerComponentWithRetainedProps("FractionBubble");

function make(step, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */(function (param) {
              var newSelf = param[/* newSelf */1];
              if (param[/* oldSelf */0][/* retainedProps */2][/* step */0] !== newSelf[/* retainedProps */2][/* step */0]) {
                var match = newSelf[/* retainedProps */2][/* step */0];
                if (match > 2 || match < 0) {
                  throw [
                        Caml_builtin_exceptions.match_failure,
                        /* tuple */[
                          "FractionBubble.re",
                          58,
                          40
                        ]
                      ];
                } else {
                  switch (match) {
                    case 0 : 
                        Curry._1(newSelf[/* send */3], /* ResetValue */0);
                        return Curry._1(newSelf[/* send */3], /* TriggerAnim */Block.__(0, [false]));
                    case 1 : 
                        Curry._1(newSelf[/* send */3], /* ResetValue */0);
                        Curry._1(newSelf[/* send */3], /* TriggerAnim */Block.__(0, [true]));
                        return Curry._1(newSelf[/* send */3], /* SetMessage */Block.__(1, ["1/3"]));
                    case 2 : 
                        Curry._1(newSelf[/* send */3], /* ResetValue */0);
                        Curry._1(newSelf[/* send */3], /* TriggerAnim */Block.__(0, [true]));
                        return Curry._1(newSelf[/* send */3], /* SetMessage */Block.__(1, ["1/4"]));
                    
                  }
                }
              } else {
                return 0;
              }
            }),
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              var match = self[/* state */1][/* onScreen */0];
              var match$1 = self[/* state */1][/* onScreen */0];
              return ReasonReact.element(undefined, undefined, Curry.app(AnimatedComponents$BsReactNative.View[/* make */0], [
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              Js_primitive.some(Style$BsReactNative.style(/* :: */[
                                        Style$BsReactNative.borderColor(Colors.lemonTea),
                                        /* :: */[
                                          Style$BsReactNative.borderWidth(4),
                                          /* :: */[
                                            Style$BsReactNative.position(/* Absolute */0),
                                            /* :: */[
                                              Style$BsReactNative.justifyContent(/* Center */2),
                                              /* :: */[
                                                Style$BsReactNative.right(/* Pt */Block.__(0, [100])),
                                                /* :: */[
                                                  Style$BsReactNative.top(/* Pt */Block.__(0, [0])),
                                                  /* :: */[
                                                    Style$BsReactNative.alignItems(/* Center */2),
                                                    /* :: */[
                                                      Style$BsReactNative.borderRadius(100 / 2),
                                                      /* :: */[
                                                        Style$BsReactNative.width(/* Pt */Block.__(0, [100 / 2])),
                                                        /* :: */[
                                                          Style$BsReactNative.height(/* Pt */Block.__(0, [100 / 2])),
                                                          /* :: */[
                                                            Style$BsReactNative.backgroundColor(Colors.oyster),
                                                            /* :: */[
                                                              Style$BsReactNative.Transform[/* makeInterpolated */2](undefined, undefined, undefined, undefined, undefined, Js_primitive.some(Curry._8(Animated$BsReactNative.Value[/* interpolate */10], self[/* state */1][/* scale */1], /* :: */[
                                                                            0,
                                                                            /* :: */[
                                                                              1,
                                                                              /* [] */0
                                                                            ]
                                                                          ], /* `float */[
                                                                            43435420,
                                                                            match ? /* :: */[
                                                                                0,
                                                                                /* :: */[
                                                                                  1,
                                                                                  /* [] */0
                                                                                ]
                                                                              ] : /* :: */[
                                                                                1,
                                                                                /* :: */[
                                                                                  0,
                                                                                  /* [] */0
                                                                                ]
                                                                              ]
                                                                          ], undefined, undefined, undefined, undefined, /* () */0)), Js_primitive.some(Curry._8(Animated$BsReactNative.Value[/* interpolate */10], self[/* state */1][/* scale */1], /* :: */[
                                                                            0,
                                                                            /* :: */[
                                                                              1,
                                                                              /* [] */0
                                                                            ]
                                                                          ], /* `float */[
                                                                            43435420,
                                                                            match$1 ? /* :: */[
                                                                                0,
                                                                                /* :: */[
                                                                                  1,
                                                                                  /* [] */0
                                                                                ]
                                                                              ] : /* :: */[
                                                                                1,
                                                                                /* :: */[
                                                                                  0,
                                                                                  /* [] */0
                                                                                ]
                                                                              ]
                                                                          ], undefined, undefined, undefined, undefined, /* () */0)), undefined, undefined, undefined, undefined, /* () */0),
                                                              /* [] */0
                                                            ]
                                                          ]
                                                        ]
                                                      ]
                                                    ]
                                                  ]
                                                ]
                                              ]
                                            ]
                                          ]
                                        ]
                                      ])),
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              /* array */[ReasonReact.element(undefined, undefined, Text$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(Style$BsReactNative.style(/* :: */[
                                                  Style$BsReactNative.color(/* String */Block.__(0, ["white"])),
                                                  /* :: */[
                                                    Style$BsReactNative.fontSize(/* Float */Block.__(0, [14])),
                                                    /* [] */0
                                                  ]
                                                ])), undefined, undefined, undefined, undefined, undefined, undefined, self[/* state */1][/* message */2], /* array */[]))]
                            ]));
            }),
          /* initialState */(function () {
              return /* record */[
                      /* onScreen */false,
                      /* scale */Curry._1(Animated$BsReactNative.Value[/* create */0], 1),
                      /* message */""
                    ];
            }),
          /* retainedProps : record */[/* step */step],
          /* reducer */(function (action, state) {
              if (typeof action === "number") {
                return /* Update */Block.__(0, [/* record */[
                            /* onScreen */state[/* onScreen */0],
                            /* scale */Curry._1(Animated$BsReactNative.Value[/* create */0], 0),
                            /* message */state[/* message */2]
                          ]]);
              } else if (action.tag) {
                return /* Update */Block.__(0, [/* record */[
                            /* onScreen */state[/* onScreen */0],
                            /* scale */state[/* scale */1],
                            /* message */action[0]
                          ]]);
              } else {
                var animation = Animated$BsReactNative.timing(state[/* scale */1], /* `raw */[
                      5690856,
                      1.0
                    ], undefined, 300.0, undefined, undefined, undefined, undefined, undefined, /* () */0);
                Animated$BsReactNative.start(animation, undefined, (console.log("Complete in bubble"), /* () */0));
                return /* Update */Block.__(0, [/* record */[
                            /* onScreen */action[0],
                            /* scale */state[/* scale */1],
                            /* message */state[/* message */2]
                          ]]);
              }
            }),
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

var reverser = /* record */[
  /* forward : :: */[
    0,
    /* :: */[
      1,
      /* [] */0
    ]
  ],
  /* backwards : :: */[
    1,
    /* :: */[
      0,
      /* [] */0
    ]
  ]
];

var circleDiameter = 100;

exports.reverser = reverser;
exports.component = component;
exports.circleDiameter = circleDiameter;
exports.make = make;
/* component Not a pure module */
