// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Parse = require("./Parse.js");
var Colors = require("./Colors.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Ingridients = require("./Ingridients.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var FractionBubble = require("./FractionBubble.js");
var VerticalSlider = require("./VerticalSlider.js");
var Text$BsReactNative = require("bs-react-native/lib/js/src/components/text.js");
var View$BsReactNative = require("bs-react-native/lib/js/src/components/view.js");
var IngridientViewPager = require("./IngridientViewPager.js");
var Style$BsReactNative = require("bs-react-native/lib/js/src/style.js");
var Animated$BsReactNative = require("bs-react-native/lib/js/src/animated.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");
var ViewPagerAndroid$BsReactNative = require("bs-react-native/lib/js/src/components/viewPagerAndroid.js");

function convertIndex(index) {
  if (index > 2 || index < 0) {
    throw [
          Caml_builtin_exceptions.match_failure,
          /* tuple */[
            "IngridientTab.re",
            25,
            4
          ]
        ];
  } else {
    return index;
  }
}

var container = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.flex(9),
      /* :: */[
        Style$BsReactNative.flexDirection(/* Row */0),
        /* :: */[
          Style$BsReactNative.justifyContent(/* FlexStart */0),
          /* :: */[
            Style$BsReactNative.padding(/* Pt */Block.__(0, [10])),
            /* :: */[
              Style$BsReactNative.backgroundColor(/* String */Block.__(0, ["#EAE2D6"])),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var rightPanel = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.flex(1),
      /* :: */[
        Style$BsReactNative.flexDirection(/* Column */2),
        /* :: */[
          Style$BsReactNative.backgroundColor(/* String */Block.__(0, ["#EAE2D6"])),
          /* [] */0
        ]
      ]
    ]);

var bottomTab = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.backgroundColor(/* String */Block.__(0, ["#867666"])),
      /* :: */[
        Style$BsReactNative.alignItems(/* Center */2),
        /* :: */[
          Style$BsReactNative.justifyContent(/* Center */2),
          /* [] */0
        ]
      ]
    ]);

var text = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.color(/* String */Block.__(0, ["#fff"])),
      /* :: */[
        Style$BsReactNative.fontSize(/* Float */Block.__(0, [24])),
        /* [] */0
      ]
    ]);

var Styles = /* module */[
  /* container */container,
  /* rightPanel */rightPanel,
  /* bottomTab */bottomTab,
  /* text */text
];

var component = ReasonReact.reducerComponent("Main");

var animatedValue = Curry._1(Animated$BsReactNative.Value[/* create */0], 1.0);

function unitFactor(unit) {
  if (unit) {
    return 0.035;
  } else {
    return 1;
  }
}

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              var match = self[/* state */1][/* measurementUnit */10];
              var match$1 = self[/* state */1][/* measurementUnit */10];
              return ReasonReact.element(undefined, undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(Style$BsReactNative.style(/* :: */[
                                        Style$BsReactNative.flex(1),
                                        /* :: */[
                                          Style$BsReactNative.paddingTop(/* Pt */Block.__(0, [10])),
                                          /* [] */0
                                        ]
                                      ])), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[
                              ReasonReact.element(undefined, undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(container), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[
                                        ReasonReact.element(undefined, undefined, VerticalSlider.make((function (step) {
                                                    Curry._1(self[/* send */3], /* UpdateInitialAmount */Block.__(2, [step]));
                                                    return Curry._1(self[/* send */3], /* UpdateConvertedAmount */Block.__(1, [step]));
                                                  }), (function (horizontalStep) {
                                                    Curry._1(self[/* send */3], /* ChangeSliderUnit */Block.__(3, [horizontalStep]));
                                                    console.log("Horizontal step: " + String(horizontalStep));
                                                    return /* () */0;
                                                  }), (function (hasFocus) {
                                                    return Curry._1(self[/* send */3], /* UpdateSliderFocus */Block.__(7, [hasFocus]));
                                                  }), /* array */[])),
                                        ReasonReact.element(undefined, undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(rightPanel), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[
                                                  ReasonReact.element(undefined, undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(Style$BsReactNative.style(/* :: */[
                                                                      Style$BsReactNative.flex(1),
                                                                      /* :: */[
                                                                        Style$BsReactNative.justifyContent(/* FlexStart */0),
                                                                        /* :: */[
                                                                          Style$BsReactNative.alignItems(/* FlexEnd */1),
                                                                          /* :: */[
                                                                            Style$BsReactNative.paddingTop(/* Pt */Block.__(0, [30])),
                                                                            /* :: */[
                                                                              Style$BsReactNative.marginRight(/* Pt */Block.__(0, [20])),
                                                                              /* [] */0
                                                                            ]
                                                                          ]
                                                                        ]
                                                                      ]
                                                                    ])), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[
                                                            ReasonReact.element(undefined, undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(Style$BsReactNative.style(/* :: */[
                                                                                Style$BsReactNative.borderColor(/* String */Block.__(0, ["#E1B80D"])),
                                                                                /* :: */[
                                                                                  Style$BsReactNative.borderWidth(4),
                                                                                  /* :: */[
                                                                                    Style$BsReactNative.position(/* Absolute */0),
                                                                                    /* :: */[
                                                                                      Style$BsReactNative.justifyContent(/* Center */2),
                                                                                      /* :: */[
                                                                                        Style$BsReactNative.alignItems(/* Center */2),
                                                                                        /* :: */[
                                                                                          Style$BsReactNative.borderRadius(120),
                                                                                          /* :: */[
                                                                                            Style$BsReactNative.width(/* Pt */Block.__(0, [120])),
                                                                                            /* :: */[
                                                                                              Style$BsReactNative.height(/* Pt */Block.__(0, [120])),
                                                                                              /* :: */[
                                                                                                Style$BsReactNative.backgroundColor(/* String */Block.__(0, ["#D5C3AA"])),
                                                                                                /* [] */0
                                                                                              ]
                                                                                            ]
                                                                                          ]
                                                                                        ]
                                                                                      ]
                                                                                    ]
                                                                                  ]
                                                                                ]
                                                                              ])), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[
                                                                      ReasonReact.element(undefined, undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(Style$BsReactNative.style(/* [] */0)), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[ReasonReact.element(undefined, undefined, Text$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(Style$BsReactNative.style(/* :: */[
                                                                                                  Style$BsReactNative.color(/* String */Block.__(0, ["white"])),
                                                                                                  /* :: */[
                                                                                                    Style$BsReactNative.fontSize(/* Float */Block.__(0, [20])),
                                                                                                    /* :: */[
                                                                                                      Style$BsReactNative.marginTop(/* Pt */Block.__(0, [-25])),
                                                                                                      /* [] */0
                                                                                                    ]
                                                                                                  ]
                                                                                                ])), undefined, undefined, undefined, undefined, undefined, undefined, "Cups", /* array */[]))])),
                                                                      ReasonReact.element(undefined, undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[ReasonReact.element(undefined, undefined, Text$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(Style$BsReactNative.style(/* :: */[
                                                                                                  Style$BsReactNative.color(/* String */Block.__(0, ["white"])),
                                                                                                  /* :: */[
                                                                                                    Style$BsReactNative.fontSize(/* Float */Block.__(0, [20 + 10])),
                                                                                                    /* :: */[
                                                                                                      Style$BsReactNative.marginLeft(/* Pt */Block.__(0, [120 / 2.5])),
                                                                                                      /* [] */0
                                                                                                    ]
                                                                                                  ]
                                                                                                ])), undefined, undefined, undefined, undefined, undefined, undefined, Parse.message(self[/* state */1][/* initial */1]), /* array */[]))]))
                                                                    ])),
                                                            ReasonReact.element(undefined, undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(Style$BsReactNative.style(/* :: */[
                                                                                Style$BsReactNative.right(/* Pt */Block.__(0, [120 / 3])),
                                                                                /* :: */[
                                                                                  Style$BsReactNative.top(/* Pt */Block.__(0, [120 / 2.5])),
                                                                                  /* :: */[
                                                                                    Style$BsReactNative.borderColor(/* String */Block.__(0, ["#E1B80D"])),
                                                                                    /* :: */[
                                                                                      Style$BsReactNative.borderWidth(8),
                                                                                      /* :: */[
                                                                                        Style$BsReactNative.position(/* Absolute */0),
                                                                                        /* :: */[
                                                                                          Style$BsReactNative.justifyContent(/* Center */2),
                                                                                          /* :: */[
                                                                                            Style$BsReactNative.alignItems(/* Center */2),
                                                                                            /* :: */[
                                                                                              Style$BsReactNative.borderRadius(120),
                                                                                              /* :: */[
                                                                                                Style$BsReactNative.width(/* Pt */Block.__(0, [120])),
                                                                                                /* :: */[
                                                                                                  Style$BsReactNative.height(/* Pt */Block.__(0, [120])),
                                                                                                  /* :: */[
                                                                                                    Style$BsReactNative.backgroundColor(/* String */Block.__(0, ["#D5C3AA"])),
                                                                                                    /* [] */0
                                                                                                  ]
                                                                                                ]
                                                                                              ]
                                                                                            ]
                                                                                          ]
                                                                                        ]
                                                                                      ]
                                                                                    ]
                                                                                  ]
                                                                                ]
                                                                              ])), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[ReasonReact.element(undefined, undefined, Text$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(Style$BsReactNative.style(/* :: */[
                                                                                        Style$BsReactNative.color(/* String */Block.__(0, ["white"])),
                                                                                        /* :: */[
                                                                                          Style$BsReactNative.fontSize(/* Float */Block.__(0, [20 + 5])),
                                                                                          /* [] */0
                                                                                        ]
                                                                                      ])), undefined, undefined, undefined, undefined, undefined, undefined, Pervasives.string_of_float(Parse.value(self[/* state */1][/* converted */2], Ingridients.find(self[/* state */1][/* currentIngridient */8])[/* density */1], self[/* state */1][/* measurementUnit */10] ? 0.035 : 1)) + (
                                                                                match ? " oz." : " gr."
                                                                              ), /* array */[]))])),
                                                            ReasonReact.element(undefined, undefined, FractionBubble.make(Style$BsReactNative.style(/* :: */[
                                                                          Style$BsReactNative.borderColor(Colors.lemonTea),
                                                                          /* :: */[
                                                                            Style$BsReactNative.borderWidth(4),
                                                                            /* :: */[
                                                                              Style$BsReactNative.position(/* Absolute */0),
                                                                              /* :: */[
                                                                                Style$BsReactNative.right(/* Pt */Block.__(0, [120])),
                                                                                /* :: */[
                                                                                  Style$BsReactNative.top(/* Pt */Block.__(0, [0])),
                                                                                  /* :: */[
                                                                                    Style$BsReactNative.backgroundColor(Colors.oyster),
                                                                                    /* [] */0
                                                                                  ]
                                                                                ]
                                                                              ]
                                                                            ]
                                                                          ]
                                                                        ]), match$1 ? "Oz" : "Kg", (function () {
                                                                        return Curry._1(self[/* send */3], /* ChangeMesurementUnit */Block.__(8, [self[/* state */1][/* measurementUnit */10]]));
                                                                      }), 120 / 2, /* array */[])),
                                                            ReasonReact.element(undefined, undefined, FractionBubble.make(Style$BsReactNative.style(/* :: */[
                                                                          Style$BsReactNative.borderColor(Colors.lemonTea),
                                                                          /* :: */[
                                                                            Style$BsReactNative.borderWidth(4),
                                                                            /* :: */[
                                                                              Style$BsReactNative.position(/* Absolute */0),
                                                                              /* :: */[
                                                                                Style$BsReactNative.right(/* Pt */Block.__(0, [-17.5])),
                                                                                /* :: */[
                                                                                  Style$BsReactNative.top(/* Pt */Block.__(0, [120 * 0.93])),
                                                                                  /* :: */[
                                                                                    Style$BsReactNative.backgroundColor(Colors.oyster),
                                                                                    /* [] */0
                                                                                  ]
                                                                                ]
                                                                              ]
                                                                            ]
                                                                          ]
                                                                        ]), "+/- 1", (function () {
                                                                        return Curry._1(self[/* send */3], /* ChangeMesurementUnit */Block.__(8, [self[/* state */1][/* measurementUnit */10]]));
                                                                      }), 120 / 2, /* array */[]))
                                                          ])),
                                                  ReasonReact.element(undefined, undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(Style$BsReactNative.style(/* :: */[
                                                                      Style$BsReactNative.flex(2),
                                                                      /* :: */[
                                                                        Style$BsReactNative.marginBottom(/* Pt */Block.__(0, [50])),
                                                                        /* [] */0
                                                                      ]
                                                                    ])), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[ReasonReact.element(undefined, undefined, IngridientViewPager.make(undefined, self[/* state */1][/* translateX */5], self[/* state */1][/* currentIngridient */8], /* array */[]))]))
                                                ]))
                                      ])),
                              ReasonReact.element(undefined, undefined, ViewPagerAndroid$BsReactNative.make(0, undefined, (function ($$event) {
                                            Curry._1(self[/* send */3], /* UpdateAnimatedValue */Block.__(4, [$$event.nativeEvent.offset]));
                                            if ($$event.nativeEvent.position !== self[/* state */1][/* currentIngridient */8]) {
                                              return Curry._1(self[/* send */3], /* SetCurrentIngridient */Block.__(6, [$$event.nativeEvent.position]));
                                            } else {
                                              return 0;
                                            }
                                          }), undefined, undefined, undefined, true, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(Style$BsReactNative.style(/* :: */[
                                                  Style$BsReactNative.flex(1),
                                                  /* :: */[
                                                    Style$BsReactNative.height(/* Pt */Block.__(0, [150])),
                                                    /* [] */0
                                                  ]
                                                ])), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[
                                        ReasonReact.element("0", undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(bottomTab), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[ReasonReact.element(undefined, undefined, Text$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(Style$BsReactNative.style(/* :: */[
                                                                    Style$BsReactNative.fontSize(/* Float */Block.__(0, [18])),
                                                                    /* :: */[
                                                                      Style$BsReactNative.color(/* String */Block.__(0, ["white"])),
                                                                      /* [] */0
                                                                    ]
                                                                  ])), undefined, undefined, undefined, undefined, undefined, undefined, "Milk", /* array */[]))])),
                                        ReasonReact.element("1", undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(bottomTab), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[ReasonReact.element(undefined, undefined, Text$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(Style$BsReactNative.style(/* :: */[
                                                                    Style$BsReactNative.fontSize(/* Float */Block.__(0, [18])),
                                                                    /* :: */[
                                                                      Style$BsReactNative.color(/* String */Block.__(0, ["white"])),
                                                                      /* [] */0
                                                                    ]
                                                                  ])), undefined, undefined, undefined, undefined, undefined, undefined, "Flour", /* array */[]))])),
                                        ReasonReact.element("2", undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(bottomTab), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[ReasonReact.element(undefined, undefined, Text$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(Style$BsReactNative.style(/* :: */[
                                                                    Style$BsReactNative.fontSize(/* Float */Block.__(0, [18])),
                                                                    /* :: */[
                                                                      Style$BsReactNative.color(/* String */Block.__(0, ["white"])),
                                                                      /* [] */0
                                                                    ]
                                                                  ])), undefined, undefined, undefined, undefined, undefined, undefined, "Butter", /* array */[]))])),
                                        ReasonReact.element("3", undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(bottomTab), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[ReasonReact.element(undefined, undefined, Text$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(Style$BsReactNative.style(/* :: */[
                                                                    Style$BsReactNative.fontSize(/* Float */Block.__(0, [18])),
                                                                    /* :: */[
                                                                      Style$BsReactNative.color(/* String */Block.__(0, ["white"])),
                                                                      /* [] */0
                                                                    ]
                                                                  ])), undefined, undefined, undefined, undefined, undefined, undefined, "Baking Soda", /* array */[]))])),
                                        ReasonReact.element("4", undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(bottomTab), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[ReasonReact.element(undefined, undefined, Text$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(Style$BsReactNative.style(/* :: */[
                                                                    Style$BsReactNative.fontSize(/* Float */Block.__(0, [18])),
                                                                    /* :: */[
                                                                      Style$BsReactNative.color(/* String */Block.__(0, ["white"])),
                                                                      /* [] */0
                                                                    ]
                                                                  ])), undefined, undefined, undefined, undefined, undefined, undefined, "Cocoa", /* array */[]))])),
                                        ReasonReact.element("5", undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(bottomTab), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[ReasonReact.element(undefined, undefined, Text$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(Style$BsReactNative.style(/* :: */[
                                                                    Style$BsReactNative.fontSize(/* Float */Block.__(0, [18])),
                                                                    /* :: */[
                                                                      Style$BsReactNative.color(/* String */Block.__(0, ["white"])),
                                                                      /* [] */0
                                                                    ]
                                                                  ])), undefined, undefined, undefined, undefined, undefined, undefined, "Cream", /* array */[]))])),
                                        ReasonReact.element("6", undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(bottomTab), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[ReasonReact.element(undefined, undefined, Text$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(Style$BsReactNative.style(/* :: */[
                                                                    Style$BsReactNative.fontSize(/* Float */Block.__(0, [18])),
                                                                    /* :: */[
                                                                      Style$BsReactNative.color(/* String */Block.__(0, ["white"])),
                                                                      /* [] */0
                                                                    ]
                                                                  ])), undefined, undefined, undefined, undefined, undefined, undefined, "Oil", /* array */[]))])),
                                        ReasonReact.element("7", undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(bottomTab), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[ReasonReact.element(undefined, undefined, Text$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(Style$BsReactNative.style(/* :: */[
                                                                    Style$BsReactNative.fontSize(/* Float */Block.__(0, [18])),
                                                                    /* :: */[
                                                                      Style$BsReactNative.color(/* String */Block.__(0, ["white"])),
                                                                      /* [] */0
                                                                    ]
                                                                  ])), undefined, undefined, undefined, undefined, undefined, undefined, "Powdered Sugar", /* array */[]))])),
                                        ReasonReact.element("8", undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(bottomTab), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[ReasonReact.element(undefined, undefined, Text$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(Style$BsReactNative.style(/* :: */[
                                                                    Style$BsReactNative.fontSize(/* Float */Block.__(0, [18])),
                                                                    /* :: */[
                                                                      Style$BsReactNative.color(/* String */Block.__(0, ["white"])),
                                                                      /* [] */0
                                                                    ]
                                                                  ])), undefined, undefined, undefined, undefined, undefined, undefined, "Sugar", /* array */[]))]))
                                      ]))
                            ]));
            }),
          /* initialState */(function () {
              return /* record */[
                      /* algo */0,
                      /* initial */0,
                      /* converted */0,
                      /* sliderUnit */0,
                      /* sliderUnitMessage */"Half a cup (1/2)",
                      /* translateX */0,
                      /* imageContainerWidth */0,
                      /* ingridientAssets : record */[
                        /* first */require("../../../assets/flour.png"),
                        /* second */require("../../../assets/butter.png")
                      ],
                      /* currentIngridient */0,
                      /* sliderHasFocus */false,
                      /* measurementUnit : Metric */0
                    ];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              switch (action.tag | 0) {
                case 0 : 
                    return /* Update */Block.__(0, [/* record */[
                                /* algo */action[0],
                                /* initial */state[/* initial */1],
                                /* converted */state[/* converted */2],
                                /* sliderUnit */state[/* sliderUnit */3],
                                /* sliderUnitMessage */state[/* sliderUnitMessage */4],
                                /* translateX */state[/* translateX */5],
                                /* imageContainerWidth */state[/* imageContainerWidth */6],
                                /* ingridientAssets */state[/* ingridientAssets */7],
                                /* currentIngridient */state[/* currentIngridient */8],
                                /* sliderHasFocus */state[/* sliderHasFocus */9],
                                /* measurementUnit */state[/* measurementUnit */10]
                              ]]);
                case 1 : 
                    return /* Update */Block.__(0, [/* record */[
                                /* algo */state[/* algo */0],
                                /* initial */state[/* initial */1],
                                /* converted */action[0],
                                /* sliderUnit */state[/* sliderUnit */3],
                                /* sliderUnitMessage */state[/* sliderUnitMessage */4],
                                /* translateX */state[/* translateX */5],
                                /* imageContainerWidth */state[/* imageContainerWidth */6],
                                /* ingridientAssets */state[/* ingridientAssets */7],
                                /* currentIngridient */state[/* currentIngridient */8],
                                /* sliderHasFocus */state[/* sliderHasFocus */9],
                                /* measurementUnit */state[/* measurementUnit */10]
                              ]]);
                case 2 : 
                    return /* Update */Block.__(0, [/* record */[
                                /* algo */state[/* algo */0],
                                /* initial */action[0],
                                /* converted */state[/* converted */2],
                                /* sliderUnit */state[/* sliderUnit */3],
                                /* sliderUnitMessage */state[/* sliderUnitMessage */4],
                                /* translateX */state[/* translateX */5],
                                /* imageContainerWidth */state[/* imageContainerWidth */6],
                                /* ingridientAssets */state[/* ingridientAssets */7],
                                /* currentIngridient */state[/* currentIngridient */8],
                                /* sliderHasFocus */state[/* sliderHasFocus */9],
                                /* measurementUnit */state[/* measurementUnit */10]
                              ]]);
                case 3 : 
                    var u = action[0];
                    var message;
                    if (u > 2 || u < 0) {
                      throw [
                            Caml_builtin_exceptions.match_failure,
                            /* tuple */[
                              "IngridientTab.re",
                              149,
                              8
                            ]
                          ];
                    } else {
                      switch (u) {
                        case 0 : 
                            message = "Half cup (1/2)";
                            break;
                        case 1 : 
                            message = "Third cup (3/2)";
                            break;
                        case 2 : 
                            message = "Quarter cup (4/2)";
                            break;
                        
                      }
                    }
                    return /* Update */Block.__(0, [/* record */[
                                /* algo */state[/* algo */0],
                                /* initial */state[/* initial */1],
                                /* converted */state[/* converted */2],
                                /* sliderUnit */u,
                                /* sliderUnitMessage */message,
                                /* translateX */state[/* translateX */5],
                                /* imageContainerWidth */state[/* imageContainerWidth */6],
                                /* ingridientAssets */state[/* ingridientAssets */7],
                                /* currentIngridient */state[/* currentIngridient */8],
                                /* sliderHasFocus */state[/* sliderHasFocus */9],
                                /* measurementUnit */state[/* measurementUnit */10]
                              ]]);
                case 4 : 
                    return /* Update */Block.__(0, [/* record */[
                                /* algo */state[/* algo */0],
                                /* initial */state[/* initial */1],
                                /* converted */state[/* converted */2],
                                /* sliderUnit */state[/* sliderUnit */3],
                                /* sliderUnitMessage */state[/* sliderUnitMessage */4],
                                /* translateX */action[0],
                                /* imageContainerWidth */state[/* imageContainerWidth */6],
                                /* ingridientAssets */state[/* ingridientAssets */7],
                                /* currentIngridient */state[/* currentIngridient */8],
                                /* sliderHasFocus */state[/* sliderHasFocus */9],
                                /* measurementUnit */state[/* measurementUnit */10]
                              ]]);
                case 5 : 
                    return /* Update */Block.__(0, [/* record */[
                                /* algo */state[/* algo */0],
                                /* initial */state[/* initial */1],
                                /* converted */state[/* converted */2],
                                /* sliderUnit */state[/* sliderUnit */3],
                                /* sliderUnitMessage */state[/* sliderUnitMessage */4],
                                /* translateX */state[/* translateX */5],
                                /* imageContainerWidth */action[0],
                                /* ingridientAssets */state[/* ingridientAssets */7],
                                /* currentIngridient */state[/* currentIngridient */8],
                                /* sliderHasFocus */state[/* sliderHasFocus */9],
                                /* measurementUnit */state[/* measurementUnit */10]
                              ]]);
                case 6 : 
                    return /* Update */Block.__(0, [/* record */[
                                /* algo */state[/* algo */0],
                                /* initial */state[/* initial */1],
                                /* converted */state[/* converted */2],
                                /* sliderUnit */state[/* sliderUnit */3],
                                /* sliderUnitMessage */state[/* sliderUnitMessage */4],
                                /* translateX */state[/* translateX */5],
                                /* imageContainerWidth */state[/* imageContainerWidth */6],
                                /* ingridientAssets */state[/* ingridientAssets */7],
                                /* currentIngridient */action[0],
                                /* sliderHasFocus */state[/* sliderHasFocus */9],
                                /* measurementUnit */state[/* measurementUnit */10]
                              ]]);
                case 7 : 
                    return /* Update */Block.__(0, [/* record */[
                                /* algo */state[/* algo */0],
                                /* initial */state[/* initial */1],
                                /* converted */state[/* converted */2],
                                /* sliderUnit */state[/* sliderUnit */3],
                                /* sliderUnitMessage */state[/* sliderUnitMessage */4],
                                /* translateX */state[/* translateX */5],
                                /* imageContainerWidth */state[/* imageContainerWidth */6],
                                /* ingridientAssets */state[/* ingridientAssets */7],
                                /* currentIngridient */state[/* currentIngridient */8],
                                /* sliderHasFocus */action[0],
                                /* measurementUnit */state[/* measurementUnit */10]
                              ]]);
                case 8 : 
                    var newUnit = action[0] ? /* Metric */0 : /* Imperial */1;
                    return /* Update */Block.__(0, [/* record */[
                                /* algo */state[/* algo */0],
                                /* initial */state[/* initial */1],
                                /* converted */state[/* converted */2],
                                /* sliderUnit */state[/* sliderUnit */3],
                                /* sliderUnitMessage */state[/* sliderUnitMessage */4],
                                /* translateX */state[/* translateX */5],
                                /* imageContainerWidth */state[/* imageContainerWidth */6],
                                /* ingridientAssets */state[/* ingridientAssets */7],
                                /* currentIngridient */state[/* currentIngridient */8],
                                /* sliderHasFocus */state[/* sliderHasFocus */9],
                                /* measurementUnit */newUnit
                              ]]);
                
              }
            }),
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

var circleDiameter = 120;

var textSize = 20;

exports.convertIndex = convertIndex;
exports.Styles = Styles;
exports.component = component;
exports.circleDiameter = circleDiameter;
exports.textSize = textSize;
exports.animatedValue = animatedValue;
exports.unitFactor = unitFactor;
exports.make = make;
/* container Not a pure module */
