// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");

var ingridients = /* array */[
  /* record */[
    /* name */"Milk",
    /* density */240.0,
    /* image */require("../../../assets/milk.png"),
    /* unit */"Cups",
    /* uuid */0
  ],
  /* record */[
    /* name */"Flour",
    /* density */128.0,
    /* image */require("../../../assets/flour.png"),
    /* unit */"Cups",
    /* uuid */1
  ],
  /* record */[
    /* name */"Butter",
    /* density */227.0,
    /* image */require("../../../assets/butter.png"),
    /* unit */"Cups",
    /* uuid */2
  ],
  /* record */[
    /* name */"Baking Soda",
    /* density */180.0,
    /* image */require("../../../assets/baking_soda.png"),
    /* unit */"Cups",
    /* uuid */3
  ],
  /* record */[
    /* name */"Cocoa",
    /* density */125.0,
    /* image */require("../../../assets/cocoa.png"),
    /* unit */"Cups",
    /* uuid */4
  ],
  /* record */[
    /* name */"Cream",
    /* density */238.0,
    /* image */require("../../../assets/cream.png"),
    /* unit */"Cups",
    /* uuid */5
  ],
  /* record */[
    /* name */"Oil",
    /* density */224.0,
    /* image */require("../../../assets/oil.png"),
    /* unit */"Cups",
    /* uuid */6
  ],
  /* record */[
    /* name */"Powdered Sugar",
    /* density */128.0,
    /* image */require("../../../assets/pow_sugar.png"),
    /* unit */"Cups",
    /* uuid */7
  ],
  /* record */[
    /* name */"Sugar",
    /* density */201.0,
    /* image */require("../../../assets/sugar.png"),
    /* unit */"Cups",
    /* uuid */8
  ],
  /* record */[
    /* name */"Sugar",
    /* density */0.14,
    /* image */require("../../../assets/sugar.png"),
    /* unit */"Cups",
    /* uuid */9
  ]
];

function find(uuid) {
  return List.find((function (ingridient) {
                return ingridient[/* uuid */4] === uuid;
              }), $$Array.to_list(ingridients));
}

var lenght = List.length($$Array.to_list(ingridients));

function getForgroundData(step, w) {
  var match = step % 2 === 0;
  var even = match ? true : false;
  return /* record */[
          /* imageResource */find(even ? step : step + 1 | 0)[/* image */2],
          /* coordinates */even ? /* :: */[
              0,
              /* :: */[
                1 * w,
                /* [] */0
              ]
            ] : /* :: */[
              1 * w,
              /* :: */[
                0,
                /* [] */0
              ]
            ]
        ];
}

function getBackgroundData(step, w) {
  var match = step % 2 === 0;
  var even = match ? true : false;
  var match$1 = !even;
  return /* record */[
          /* imageResource */find(match$1 ? step : step + 1 | 0)[/* image */2],
          /* coordinates */even ? /* :: */[
              0,
              /* :: */[
                -1 * w,
                /* [] */0
              ]
            ] : /* :: */[
              -1 * w,
              /* :: */[
                0,
                /* [] */0
              ]
            ]
        ];
}

exports.ingridients = ingridients;
exports.find = find;
exports.lenght = lenght;
exports.getForgroundData = getForgroundData;
exports.getBackgroundData = getBackgroundData;
/* ingridients Not a pure module */
