// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Colors = require("./Colors.js");
var Ingridients = require("./Ingridients.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var View$BsReactNative = require("bs-react-native/lib/js/src/components/view.js");
var Style$BsReactNative = require("bs-react-native/lib/js/src/style.js");
var RNEvent$BsReactNative = require("bs-react-native/lib/js/src/RNEvent.js");
var Animated$BsReactNative = require("bs-react-native/lib/js/src/animated.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");
var AnimatedComponents$BsReactNative = require("bs-react-native/lib/js/src/components/animatedComponents.js");

function convertIndex(index) {
  if (index > 2 || index < 0) {
    throw [
          Caml_builtin_exceptions.match_failure,
          /* tuple */[
            "IngridientViewPager.re",
            29,
            4
          ]
        ];
  } else {
    switch (index) {
      case 0 : 
          return /* Flour */0;
      case 1 : 
          return /* Milk */1;
      case 2 : 
          return /* Butter */8;
      
    }
  }
}

var component = ReasonReact.reducerComponentWithRetainedProps("IngridientViewPager");

function make(_, sliderOffset, sliderPosition, _$1) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */(function (param) {
              var newSelf = param[/* newSelf */1];
              var oldSelf = param[/* oldSelf */0];
              if (oldSelf[/* retainedProps */2][/* sliderOffset */1] !== newSelf[/* retainedProps */2][/* sliderOffset */1]) {
                Curry._1(newSelf[/* send */3], /* UpdateAnimatedValue */Block.__(1, [newSelf[/* retainedProps */2][/* sliderOffset */1]]));
              }
              if (oldSelf[/* retainedProps */2][/* sliderPosition */0] !== newSelf[/* retainedProps */2][/* sliderPosition */0]) {
                return Curry._1(newSelf[/* send */3], /* UpdateImageAsset */Block.__(2, [newSelf[/* retainedProps */2][/* sliderPosition */0]]));
              } else {
                return 0;
              }
            }),
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return ReasonReact.element(undefined, undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, (function ($$event) {
                                  var layoutData = RNEvent$BsReactNative.NativeLayoutEvent[/* layout */0]($$event);
                                  return Curry._1(self[/* send */3], /* SetComponentWidth */Block.__(0, [layoutData[/* width */2]]));
                                }), undefined, undefined, undefined, undefined, Js_primitive.some(Style$BsReactNative.style(/* :: */[
                                        Style$BsReactNative.flex(1),
                                        /* [] */0
                                      ])), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[ReasonReact.element(undefined, undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(Style$BsReactNative.style(/* :: */[
                                                  Style$BsReactNative.flex(1),
                                                  /* :: */[
                                                    Style$BsReactNative.width(/* Pt */Block.__(0, [self[/* state */1][/* componentWidth */0] * 2])),
                                                    /* :: */[
                                                      Style$BsReactNative.flexDirection(/* Row */0),
                                                      /* [] */0
                                                    ]
                                                  ]
                                                ])), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[
                                        ReasonReact.element(undefined, undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(Style$BsReactNative.style(/* :: */[
                                                            Style$BsReactNative.width(/* Pt */Block.__(0, [self[/* state */1][/* componentWidth */0]])),
                                                            /* :: */[
                                                              Style$BsReactNative.justifyContent(/* Center */2),
                                                              /* :: */[
                                                                Style$BsReactNative.alignItems(/* Center */2),
                                                                /* [] */0
                                                              ]
                                                            ]
                                                          ])), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[ReasonReact.element(undefined, undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(Style$BsReactNative.style(/* :: */[
                                                                      Style$BsReactNative.backgroundColor(Colors.oyster),
                                                                      /* :: */[
                                                                        Style$BsReactNative.borderColor(Colors.lemonTea),
                                                                        /* :: */[
                                                                          Style$BsReactNative.borderWidth(4),
                                                                          /* :: */[
                                                                            Style$BsReactNative.borderRadius(self[/* state */1][/* componentWidth */0]),
                                                                            /* :: */[
                                                                              Style$BsReactNative.width(/* Pt */Block.__(0, [self[/* state */1][/* componentWidth */0] * 0.85])),
                                                                              /* :: */[
                                                                                Style$BsReactNative.height(/* Pt */Block.__(0, [self[/* state */1][/* componentWidth */0] * 0.85])),
                                                                                /* :: */[
                                                                                  Style$BsReactNative.justifyContent(/* Center */2),
                                                                                  /* :: */[
                                                                                    Style$BsReactNative.alignItems(/* Center */2),
                                                                                    /* [] */0
                                                                                  ]
                                                                                ]
                                                                              ]
                                                                            ]
                                                                          ]
                                                                        ]
                                                                      ]
                                                                    ])), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[ReasonReact.element(undefined, undefined, Curry.app(AnimatedComponents$BsReactNative.Image[/* make */5], [
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      /* stretch */-162316795,
                                                                      /* `Required */[
                                                                        202657151,
                                                                        self[/* state */1][/* foreground */2][/* imageResource */0]
                                                                      ],
                                                                      Js_primitive.some(Style$BsReactNative.style(/* :: */[
                                                                                Style$BsReactNative.height(/* Pt */Block.__(0, [180])),
                                                                                /* :: */[
                                                                                  Style$BsReactNative.width(/* Pt */Block.__(0, [180])),
                                                                                  /* :: */[
                                                                                    Style$BsReactNative.Transform[/* makeInterpolated */2](undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(Curry._8(Animated$BsReactNative.Value[/* interpolate */10], self[/* state */1][/* translateX */1], List.map((function (prim) {
                                                                                                        return prim;
                                                                                                      }), /* :: */[
                                                                                                      0,
                                                                                                      /* :: */[
                                                                                                        1,
                                                                                                        /* [] */0
                                                                                                      ]
                                                                                                    ]), /* `float */[
                                                                                                  43435420,
                                                                                                  self[/* state */1][/* foreground */2][/* coordinates */1]
                                                                                                ], undefined, undefined, undefined, undefined, /* () */0)), undefined, undefined, undefined, /* () */0),
                                                                                    /* [] */0
                                                                                  ]
                                                                                ]
                                                                              ])),
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      /* array */[]
                                                                    ]))]))])),
                                        ReasonReact.element(undefined, undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(Style$BsReactNative.style(/* :: */[
                                                            Style$BsReactNative.width(/* Pt */Block.__(0, [self[/* state */1][/* componentWidth */0]])),
                                                            /* :: */[
                                                              Style$BsReactNative.justifyContent(/* Center */2),
                                                              /* :: */[
                                                                Style$BsReactNative.alignItems(/* Center */2),
                                                                /* [] */0
                                                              ]
                                                            ]
                                                          ])), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[ReasonReact.element(undefined, undefined, Curry.app(AnimatedComponents$BsReactNative.Image[/* make */5], [
                                                            undefined,
                                                            undefined,
                                                            undefined,
                                                            undefined,
                                                            undefined,
                                                            /* stretch */-162316795,
                                                            /* `Required */[
                                                              202657151,
                                                              self[/* state */1][/* background */3][/* imageResource */0]
                                                            ],
                                                            Js_primitive.some(Style$BsReactNative.style(/* :: */[
                                                                      Style$BsReactNative.height(/* Pt */Block.__(0, [180])),
                                                                      /* :: */[
                                                                        Style$BsReactNative.width(/* Pt */Block.__(0, [180])),
                                                                        /* :: */[
                                                                          Style$BsReactNative.Transform[/* makeInterpolated */2](undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(Curry._8(Animated$BsReactNative.Value[/* interpolate */10], self[/* state */1][/* translateX */1], List.map((function (prim) {
                                                                                              return prim;
                                                                                            }), /* :: */[
                                                                                            0,
                                                                                            /* :: */[
                                                                                              1,
                                                                                              /* [] */0
                                                                                            ]
                                                                                          ]), /* `float */[
                                                                                        43435420,
                                                                                        self[/* state */1][/* background */3][/* coordinates */1]
                                                                                      ], undefined, undefined, undefined, undefined, /* () */0)), undefined, undefined, undefined, /* () */0),
                                                                          /* [] */0
                                                                        ]
                                                                      ]
                                                                    ])),
                                                            undefined,
                                                            undefined,
                                                            undefined,
                                                            undefined,
                                                            undefined,
                                                            undefined,
                                                            undefined,
                                                            undefined,
                                                            undefined,
                                                            /* array */[]
                                                          ]))]))
                                      ]))]));
            }),
          /* initialState */(function () {
              return /* record */[
                      /* componentWidth */0,
                      /* translateX */Curry._1(Animated$BsReactNative.Value[/* create */0], 0),
                      /* foreground : record */[
                        /* imageResource */Ingridients.find(0)[/* image */2],
                        /* coordinates : :: */[
                          0,
                          /* :: */[
                            0,
                            /* [] */0
                          ]
                        ]
                      ],
                      /* background : record */[
                        /* imageResource */Ingridients.find(1)[/* image */2],
                        /* coordinates : :: */[
                          0,
                          /* :: */[
                            0,
                            /* [] */0
                          ]
                        ]
                      ]
                    ];
            }),
          /* retainedProps : record */[
            /* sliderPosition */sliderPosition,
            /* sliderOffset */sliderOffset
          ],
          /* reducer */(function (action, state) {
              switch (action.tag | 0) {
                case 0 : 
                    var f = action[0];
                    return /* Update */Block.__(0, [/* record */[
                                /* componentWidth */f,
                                /* translateX */state[/* translateX */1],
                                /* foreground */Ingridients.getForgroundData(sliderPosition, f),
                                /* background */Ingridients.getBackgroundData(sliderPosition, f)
                              ]]);
                case 1 : 
                    return /* Update */Block.__(0, [/* record */[
                                /* componentWidth */state[/* componentWidth */0],
                                /* translateX */Curry._1(Animated$BsReactNative.Value[/* create */0], action[0]),
                                /* foreground */state[/* foreground */2],
                                /* background */state[/* background */3]
                              ]]);
                case 2 : 
                    var i = action[0];
                    return /* Update */Block.__(0, [/* record */[
                                /* componentWidth */state[/* componentWidth */0],
                                /* translateX */state[/* translateX */1],
                                /* foreground */Ingridients.getForgroundData(i, state[/* componentWidth */0]),
                                /* background */Ingridients.getBackgroundData(i, state[/* componentWidth */0])
                              ]]);
                
              }
            }),
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.convertIndex = convertIndex;
exports.component = component;
exports.make = make;
/* component Not a pure module */
