// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

function message(step) {
  if (step > 6 || step < 0) {
    throw [
          Caml_builtin_exceptions.match_failure,
          /* tuple */[
            "Parse.re",
            3,
            4
          ]
        ];
  } else {
    switch (step) {
      case 0 : 
          return "0";
      case 1 : 
          return "¼";
      case 2 : 
          return "⅓";
      case 3 : 
          return "½";
      case 4 : 
          return "⅔";
      case 5 : 
          return "¾";
      case 6 : 
          return "1";
      
    }
  }
}

function value(step, density, unit) {
  var value$1;
  if (step > 6 || step < 0) {
    throw [
          Caml_builtin_exceptions.match_failure,
          /* tuple */[
            "Parse.re",
            17,
            4
          ]
        ];
  } else {
    switch (step) {
      case 0 : 
          value$1 = 0;
          break;
      case 1 : 
          value$1 = 0.25;
          break;
      case 2 : 
          value$1 = 0.3;
          break;
      case 3 : 
          value$1 = 0.5;
          break;
      case 4 : 
          value$1 = 0.6;
          break;
      case 5 : 
          value$1 = 0.75;
          break;
      case 6 : 
          value$1 = 1;
          break;
      
    }
  }
  return value$1 * density * unit;
}

exports.message = message;
exports.value = value;
/* No side effect */
